# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Maven Verify"

on:
  pull_request:
    branches: [main, release-*]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Maven Java 17"
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-java17-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-java17
      - name: Build with Maven
        run: mvn -DargLine="-Xmx4096m -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:GCTimeRatio=99" -B clean verify --file pom.xml
        env:
          MAVEN_OPTS: --add-opens=java.base/sun.security.x509=ALL-UNNAMED
      - name: Upload assemblies
        uses: actions/upload-artifact@v3
        with:
          name: Assemblies
          path: |
            distribution/target/*.jar
            ia-clientlibrary/target/*.jar
            igc-clientlibrary/target/*.jar
