# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Release"

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Release"
    steps:
      - uses: actions/checkout@v3
        name: Checkout source
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          # Java 17 is used for final released build
          java-version: '17'
          distribution: 'temurin'
          # Publishing attributes for maven central (this step adds to setting.xml)
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          # Keys must be known to maven central - require broad publishing
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      # Normal build (in future may also run reports (site))
      - name: Build with Maven
        # See https://github.com/actions/toolkit/issues/231 requires parms using . to be quoted
        run: mvn -DargLine="-Xmx4096m" -B -DuseMavenCentral clean deploy
        # Needed for publishing -- note we push to a staging area, login to oss.sonatype.org to
        # verify (close) the repository & release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      # Mostly for verification - not published to the release itself for now
      - name: Upload assemblies
        uses: actions/upload-artifact@v3
        with:
          name: Assemblies
          path: |
            distribution/target/*.jar
            ia-clientlibrary/target/*.jar
            igc-clientlibrary/target/*.jar
